/* This file is auto-generated by SST during `sst dev` / `sst build`.
 * This manual version ensures `tsc --noEmit` passes without running SST.
 * Keep in sync with resources linked in infra/api.ts and infra/auth.ts.
 */

import 'sst';

declare module 'sst' {
  export interface Resource {
    GithubClientId: { value: string };
    GithubClientSecret: { value: string };
    JwtSecret: { value: string };
    Users: { name: string };
    Sessions: { name: string };
    Progress: { name: string };
  }
}
