export interface TerminalCommand {
  command: string;
  output: string | string[];
  delayBefore: number;
  typeSpeed: number;
  outputDelay: number;
  isJoke: boolean;
  prompt?: string;
}

export const terminalCommands: TerminalCommand[] = [
  {
    command: 'echo "🚀 Initializing works-on-my.cloud..."',
    output: '🚀 Initializing works-on-my.cloud...',
    delayBefore: 500,
    typeSpeed: 30,
    outputDelay: 200,
    isJoke: false,
  },
  {
    command: 'git status',
    output: [
      'On branch main',
      "Your branch is up to date with 'origin/main'.",
      '',
      'Changes not staged for commit:',
      '  modified:   src/pages/index.astro',
      '  modified:   README.md',
      '',
      'Untracked files:',
      '  src/components/terminal/',
      '',
      'no changes added to commit (use "git add" to track)',
    ],
    delayBefore: 800,
    typeSpeed: 40,
    outputDelay: 300,
    isJoke: true,
  },
  {
    command: 'docker ps -a',
    output: [
      'CONTAINER ID   IMAGE         STATUS                      NAMES',
      '3a7f8b2c1d4e   nginx:latest  Up 2 days                   web-server',
      '9e1f4a6b3c8d   redis:7       Exited (0) 3 weeks ago      redis-cache',
      '2f5d8a1c9e4b   postgres:15   Up 5 days                   db-primary',
      '7b3c9e2a4f1d   node:18       Created (never started)     test-container',
    ],
    delayBefore: 1000,
    typeSpeed: 35,
    outputDelay: 400,
    isJoke: true,
  },
  {
    command: 'kubectl get pods --all-namespaces | grep -v Running',
    output: [
      'NAMESPACE     NAME                    STATUS',
      'production    api-deployment-xyz      CrashLoopBackOff',
      'staging       worker-pod-abc          Pending',
      'default       test-pod-123           Error',
      '',
      '(Showing only non-running pods because reality hurts)',
    ],
    delayBefore: 1200,
    typeSpeed: 45,
    outputDelay: 500,
    isJoke: true,
  },
  {
    command: 'terraform plan | grep "will be" | head -5',
    output: [
      '  # aws_instance.web will be created',
      '  # aws_s3_bucket.data will be destroyed',
      '  # aws_security_group.app will be replaced',
      '  # aws_route53_record.api will be created',
      '  # aws_cloudwatch_alarm.cpu will be destroyed',
      '',
      'Plan: 2 to add, 1 to change, 2 to destroy.',
    ],
    delayBefore: 1000,
    typeSpeed: 40,
    outputDelay: 400,
    isJoke: true,
  },
  {
    command: 'npm audit --json | jq ".metadata.vulnerabilities"',
    output: [
      '{',
      '  "info": 0,',
      '  "low": 12,',
      '  "moderate": 8,',
      '  "high": 3,',
      '  "critical": 1',
      '}',
      '',
      'Run `npm audit fix`? (Good luck with that)',
    ],
    delayBefore: 1100,
    typeSpeed: 35,
    outputDelay: 500,
    isJoke: true,
  },
  {
    command: 'df -h | grep -E "^/dev" | awk \'{print $1, $5}\' | sort -k2 -rn | head -3',
    output: [
      '/dev/sda1  85%',
      '/dev/sdb1  92%',
      '/dev/sdc1  78%',
      '',
      "Those logs aren't going to delete themselves...",
    ],
    delayBefore: 900,
    typeSpeed: 50,
    outputDelay: 400,
    isJoke: true,
  },
  {
    command: 'docker images | wc -l',
    output: '47',
    delayBefore: 800,
    typeSpeed: 30,
    outputDelay: 300,
    isJoke: true,
  },
  {
    command: 'echo "You have 47 Docker images. Do you really need all of them?"',
    output: 'You have 47 Docker images. Do you really need all of them?',
    delayBefore: 500,
    typeSpeed: 40,
    outputDelay: 200,
    isJoke: true,
  },
  {
    command: 'git log --oneline --since="1 week ago" | wc -l',
    output: '23',
    delayBefore: 1000,
    typeSpeed: 30,
    outputDelay: 300,
    isJoke: true,
  },
  {
    command: 'echo "23 commits this week. Someone\'s been busy... or procrastinating."',
    output: "23 commits this week. Someone's been busy... or procrastinating.",
    delayBefore: 500,
    typeSpeed: 40,
    outputDelay: 200,
    isJoke: true,
  },
  {
    command: 'kubectl get all --all-namespaces | wc -l',
    output: '156',
    delayBefore: 1100,
    typeSpeed: 30,
    outputDelay: 300,
    isJoke: true,
  },
  {
    command: 'echo "156 Kubernetes resources. Is this a startup or Google?"',
    output: '156 Kubernetes resources. Is this a startup or Google?',
    delayBefore: 500,
    typeSpeed: 40,
    outputDelay: 200,
    isJoke: true,
  },
  {
    command: 'terraform state list | grep -E "(module|data)" | wc -l',
    output: '42',
    delayBefore: 1000,
    typeSpeed: 30,
    outputDelay: 300,
    isJoke: true,
  },
  {
    command: 'echo "42 modules. The answer to life, the universe, and infrastructure."',
    output: '42 modules. The answer to life, the universe, and infrastructure.',
    delayBefore: 500,
    typeSpeed: 40,
    outputDelay: 200,
    isJoke: true,
  },
  {
    command: 'docker system df',
    output: [
      'TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE',
      'Images          47        12        15.2GB    8.5GB (56%)',
      'Containers      23        3         2.1GB    1.8GB (86%)',
      'Local Volumes   8         2         500MB    400MB (80%)',
      '',
      "Run 'docker system prune -a'? (You know you want to...)",
    ],
    delayBefore: 900,
    typeSpeed: 35,
    outputDelay: 500,
    isJoke: true,
  },
  {
    command: 'echo "✨ System ready! Welcome to works-on-my.cloud"',
    output: '✨ System ready! Welcome to works-on-my.cloud',
    delayBefore: 800,
    typeSpeed: 30,
    outputDelay: 500,
    isJoke: false,
  },
];
